openapi: 3.0.2
info:
  title: Calculator API
  description: Calculator API documentation
  version: 1.0.0

paths:
  /api-docs:
    get:
      summary: OpenAPI documentation
      responses:
        200:
          description: OpenAPI documentation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenAPI'

securitySchemes:
  - bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []